// import { NextResponse } from "next/server";
// import prisma from "../../lib/prisma";

// import { Prisma } from "@prisma/client";

// import {
//   damage1,
//   damage2,
//   damage3,
//   damage4,
//   damage5,
//   damage6,
//   damage7,
//   damage8,
//   damage9,
//   damage10,
//   damage11,
//   damage12,
//   damage13,
//   damage14,
//   damage15,
//   damage16,
//   damage17,
//   damage18,
//   damage19,
//   damage20,
//   damage21,
//   damage22,
//   damage23,
//   damage24,
//   damage25,
//   damage26,
//   damage27,
//   damage28,
//   damage29,
//   damage30,
//   damage31,
//   damage32,
//   damage33,
//   damage34,
//   damage35,
//   damage36,
//   damage37,
//   damage38,
//   damage39,
//   damage40,
// } from "../../../constants/components";

// import {
//   typeOfDamage1,
//   typeOfDamage2,
//   typeOfDamage3,
//   typeOfDamage4,
//   typeOfDamage5,
//   typeOfDamage6,
//   typeOfDamage7,
//   typeOfDamage8,
//   typeOfDamage9,
//   typeOfDamage10,
//   typeOfDamage11,
//   typeOfDamage12,
//   typeOfDamage13,
//   typeOfDamage14,
//   typeOfDamage15,
//   typeOfDamage16,
//   typeOfDamage17,
//   typeOfDamage18,
//   typeOfDamage19,
//   typeOfDamage20,
//   typeOfDamage21,
//   typeOfDamage22,
//   typeOfDamage23,
//   typeOfDamage24,
//   typeOfDamage25,
//   typeOfDamage26,
//   typeOfDamage27,
//   typeOfDamage28,
//   typeOfDamage29,
//   typeOfDamage30,
//   typeOfDamage31,
//   typeOfDamage32,
//   typeOfDamage33,
//   typeOfDamage34,
//   typeOfDamage35,
//   typeOfDamage36,
//   typeOfDamage37,
//   typeOfDamage38,
//   typeOfDamage39,
// } from "../../../constants/typeofdamages";

// export const revalidate = 0;

// export async function GET(request: any) {
//   try {
//     const Toll_Component_1 = JSON.stringify({
//       component: {
//         component_details: { name: "COLUMN", tick: 0 },
//         material: [
//           {
//             rating_of_member: 0,
//             material_details: [
//               {
//                 name: "Steel",
//                 tick: 0,
//               },
//             ],
//             type_of_damages: [
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Corrosion of Steel",
//                 code: 1,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage1,
//                 type_of_damages_array: typeOfDamage1,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Fracture of Steel",
//                 code: 2,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "If detected, rating = 4",
//                 severity_of_damage_list: damage2,
//                 type_of_damages_array: typeOfDamage2,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Loose Connections",
//                 code: 3,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage3,
//                 type_of_damages_array: typeOfDamage3,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Permanent Deformations",
//                 code: 4,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "If detected, rating = 4",
//                 severity_of_damage_list: damage4,
//                 type_of_damages_array: typeOfDamage4,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Paint Deterioration",
//                 code: 5,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage5,
//                 type_of_damages_array: typeOfDamage5,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Tilt",
//                 code: 15,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "If detected, rating = 4",
//                 severity_of_damage_list: damage15,
//                 type_of_damages_array: typeOfDamage15,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Water Leak Stain",
//                 code: 31,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "If detected, rating = 4",
//                 severity_of_damage_list: damage14,
//                 type_of_damages_array: typeOfDamage14,
//               },
//             ],
//           },
//           {
//             rating_of_member: 0,
//             material_details: [
//               {
//                 name: "Concrete",
//                 tick: 0,
//               },
//             ],
//             type_of_damages: [
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Surface Defect (Honeycomb)",
//                 code: 11,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage11,
//                 type_of_damages_array: typeOfDamage11,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Cracks at Concrete",
//                 code: 6,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "If detected, rating = 4",
//                 severity_of_damage_list: damage6,
//                 type_of_damages_array: typeOfDamage6,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Delamination",
//                 code: 12,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage12,
//                 type_of_damages_array: typeOfDamage12,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Spalling",
//                 code: 7,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage7,
//                 type_of_damages_array: typeOfDamage7,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Corrosion of Reinforcement",
//                 code: 8,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage8,
//                 type_of_damages_array: typeOfDamage8,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Tilt/Settlement",
//                 code: 13,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "If detected, rating = 4",
//                 severity_of_damage_list: damage15,
//                 type_of_damages_array: typeOfDamage15,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Water Leak Stain",
//                 code: 16,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage14,
//                 type_of_damages_array: typeOfDamage14,
//               },
//             ],
//           },
//         ],
//       },
//     });

//     const Toll_Component_2 = JSON.stringify({
//       component: {
//         component_details: { name: "BEAM", tick: 0 },
//         material: [
//           {
//             rating_of_member: 0,
//             material_details: [
//               {
//                 name: "Steel",
//                 tick: 0,
//               },
//             ],
//             type_of_damages: [
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Corrosion of Steel",
//                 code: 1,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage1,
//                 type_of_damages_array: typeOfDamage1,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Fracture of Steel",
//                 code: 2,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "If detected, rating = 4",
//                 severity_of_damage_list: damage2,
//                 type_of_damages_array: typeOfDamage2,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Loose Connections",
//                 code: 3,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage3,
//                 type_of_damages_array: typeOfDamage3,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Permanent Deformations",
//                 code: 4,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "If detected, rating = 4",
//                 severity_of_damage_list: damage4,
//                 type_of_damages_array: typeOfDamage4,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Water Leak Stain",
//                 code: 14,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage14,
//                 type_of_damages_array: typeOfDamage14,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Paint Deterioration",
//                 code: 16,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "If detected, rating = 4",
//                 severity_of_damage_list: damage5,
//                 type_of_damages_array: typeOfDamage5,
//               },
//             ],
//           },
//           {
//             rating_of_member: 0,
//             material_details: [
//               {
//                 name: "Concrete",
//                 tick: 0,
//               },
//             ],
//             type_of_damages: [
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Surface Defect (Honeycomb)",
//                 code: 11,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage11,
//                 type_of_damages_array: typeOfDamage11,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Cracks at Concrete",
//                 code: 6,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage6,
//                 type_of_damages_array: typeOfDamage6,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Delamination",
//                 code: 12,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage12,
//                 type_of_damages_array: typeOfDamage12,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Spalling",
//                 code: 7,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage7,
//                 type_of_damages_array: typeOfDamage7,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Corrosion of Reinforcement",
//                 code: 8,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage8,
//                 type_of_damages_array: typeOfDamage8,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Water Leak/Free Lime",
//                 code: 14,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage14,
//                 type_of_damages_array: typeOfDamage14,
//               },
//             ],
//           },
//         ],
//       },
//     });

//     const Toll_Component_3 = JSON.stringify({
//       component: {
//         component_details: { name: "ROOF", tick: 0 },
//         material: [
//           {
//             rating_of_member: 0,
//             material_details: [
//               {
//                 name: "Tiles",
//                 tick: 0,
//               },
//               {
//                 name: "Metal Deck",
//                 tick: 0,
//               },
//             ],
//             type_of_damages: [
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Damage/Missing Panel",
//                 code: 39,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage39,
//                 type_of_damages_array: typeOfDamage39,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Corrosion",
//                 code: 8,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage8,
//                 type_of_damages_array: typeOfDamage8,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Surface Defects",
//                 code: 12,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage12,
//                 type_of_damages_array: typeOfDamage12,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Delamination",
//                 code: 12,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage12,
//                 type_of_damages_array: typeOfDamage12,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Water Leak Stain",
//                 code: 14,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage14,
//                 type_of_damages_array: typeOfDamage14,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Loose Connection",
//                 code: 3,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage3,
//                 type_of_damages_array: typeOfDamage3,
//               },
//             ],
//           },
//         ],
//       },
//     });

//     const Toll_Component_4 = JSON.stringify({
//       component: {
//         component_details: { name: "ROOF TRUSS", tick: 0 },
//         material: [
//           {
//             rating_of_member: 0,
//             pier_no: "",
//             material_details: [
//               {
//                 name: "Steel",
//                 tick: 0,
//               },
//               {
//                 name: "Timber",
//                 tick: 0,
//               },
//               {
//                 name: "Aluminium",
//                 tick: 0,
//               },
//             ],
//             type_of_damages: [
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Corrosion of Steel",
//                 code: 1,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage1,
//                 type_of_damages_array: typeOfDamage1,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Fracture",
//                 code: 2,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage2,
//                 type_of_damages_array: typeOfDamage2,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Loose Connection",
//                 code: 3,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage3,
//                 type_of_damages_array: typeOfDamage3,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Paint Deterioration",
//                 code: 5,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage5,
//                 type_of_damages_array: typeOfDamage5,
//               },
//             ],
//           },
//         ],
//       },
//     });

//     const Toll_Component_5 = JSON.stringify({
//       component: {
//         component_details: { name: "Ceiling", tick: 0 },
//         material: [
//           {
//             rating_of_member: 0,
//             material_details: [
//               {
//                 name: "Aluminium",
//                 tick: 0,
//               },
//               {
//                 name: "Steel",
//                 tick: 0,
//               },
//               {
//                 name: "Others",
//                 tick: 0,
//               },
//             ],
//             type_of_damages: [
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Corrosion",
//                 code: 1,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage1,
//                 type_of_damages_array: typeOfDamage1,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Loose Connection",
//                 code: 3,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage3,
//                 type_of_damages_array: typeOfDamage3,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Water Leak Stain",
//                 code: 14,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage14,
//                 type_of_damages_array: typeOfDamage14,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Paint Deterioration",
//                 code: 5,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage5,
//                 type_of_damages_array: typeOfDamage5,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Missing Panel",
//                 code: 39,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage39,
//                 type_of_damages_array: typeOfDamage39,
//               },
//             ],
//           },
//         ],
//       },
//     });

//     const Toll_Component_6 = JSON.stringify({
//       component: {
//         component_details: { name: "Roof Gutter", tick: 0 },
//         material: [
//           {
//             rating_of_member: 0,
//             material_details: [
//               {
//                 name: "Steel",
//                 tick: 0,
//               },
//               {
//                 name: "PVC",
//                 tick: 0,
//               },
//             ],
//             type_of_damages: [
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Corrosion of Steel",
//                 code: 1,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage1,
//                 type_of_damages_array: typeOfDamage1,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Fracture",
//                 code: 2,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage2,
//                 type_of_damages_array: typeOfDamage2,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Loose Connection",
//                 code: 3,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage3,
//                 type_of_damages_array: typeOfDamage3,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Paint Deterioration",
//                 code: 5,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage5,
//                 type_of_damages_array: typeOfDamage5,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Missing Panel",
//                 code: 14,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage3,
//                 type_of_damages_array: typeOfDamage3,
//               },
//             ],
//           },
//         ],
//       },
//     });

//     const Toll_Component_7 = JSON.stringify({
//       component: {
//         component_details: { name: "Roof Maintenance Access Opening", tick: 0 },
//         material: [
//           {
//             rating_of_member: 0,
//             material_details: [
//               {
//                 name: "Steel",
//                 tick: 0,
//               },
//               {
//                 name: "Stainless Steel",
//                 tick: 0,
//               },
//               {
//                 name: "Aluminium",
//                 tick: 0,
//               },
//             ],
//             type_of_damages: [
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Corrosion",
//                 code: 1,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage1,
//                 type_of_damages_array: typeOfDamage1,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Fracture",
//                 code: 2,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage2,
//                 type_of_damages_array: typeOfDamage2,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Loose Connection",
//                 code: 3,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage3,
//                 type_of_damages_array: typeOfDamage3,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Paint Deterioration",
//                 code: 5,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage5,
//                 type_of_damages_array: typeOfDamage5,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Pavement Crack",
//                 code: 14,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage14,
//                 type_of_damages_array: typeOfDamage14,
//               },
//             ],
//           },
//         ],
//       },
//     });

//     const Toll_Component_8 = JSON.stringify({
//       component: {
//         component_details: { name: "Rainwater Down Pipe", tick: 0 },
//         material: [
//           {
//             rating_of_member: 0,
//             material_details: [
//               {
//                 name: "Steel",
//                 tick: 0,
//               },
//               {
//                 name: "PVC",
//                 tick: 0,
//               },
//             ],
//             type_of_damages: [
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Corrosion",
//                 code: 1,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "if detected, rating = 4",
//                 severity_of_damage_list: damage1,
//                 type_of_damages_array: typeOfDamage1,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Blocked Drainage",
//                 code: 20,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage20,
//                 type_of_damages_array: typeOfDamage20,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Water Leak Stain",
//                 code: 14,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage14,
//                 type_of_damages_array: typeOfDamage14,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Inadequate Pipe Length",
//                 code: 21,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage21,
//                 type_of_damages_array: typeOfDamage21,
//               },
//             ],
//           },
//         ],
//       },
//     });

//     const Toll_Component_9 = JSON.stringify({
//       component: {
//         component_details: { name: "Lane-Concrete Pavement", tick: 0 },
//         material: [
//           {
//             rating_of_member: 0,
//             material_details: [
//               {
//                 name: "Asphalt",
//                 tick: 0,
//               },
//               {
//                 name: "Concrete",
//                 tick: 0,
//               },
//             ],
//             type_of_damages: [
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Pot Hole",
//                 code: 23,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage23,
//                 type_of_damages_array: typeOfDamage23,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Rutting",
//                 code: 24,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage24,
//                 type_of_damages_array: typeOfDamage24,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Pavement Crack",
//                 code: 27,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage27,
//                 type_of_damages_array: typeOfDamage27,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Delamination",
//                 code: 21,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage25,
//                 type_of_damages_array: typeOfDamage25,
//               },
//             ],
//           },
//         ],
//       },
//     });

//     const Toll_Component_10 = JSON.stringify({
//       component: {
//         component_details: {
//           name: "General Observations (Others)",
//           tick: 0,
//         },
//         material: [
//           {
//             rating_of_member: 0,
//             material_details: [
//               {
//                 name: "i)... Island",
//                 tick: 0,
//               },
//               {
//                 name: "ii)... Barrier",
//                 tick: 0,
//               },
//             ],
//             type_of_damages: [
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Corrosion",
//                 code: 1,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage1,
//                 type_of_damages_array: typeOfDamage1,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Cracks at Conrete",
//                 code: 6,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage6,
//                 type_of_damages_array: typeOfDamage6,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Spalling",
//                 code: 7,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage7,
//                 type_of_damages_array: typeOfDamage7,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Impact Damage",
//                 code: 22,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage22,
//                 type_of_damages_array: typeOfDamage22,
//               },
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Paint Deterioration",
//                 code: 5,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage5,
//                 type_of_damages_array: typeOfDamage5,
//               },
//             ],
//           },
//         ],
//       },
//     });

//     const Toll_Component_11 = JSON.stringify({
//       component: {
//         component_details: {
//           name: "HYDRAULIC CAPACITY",
//           tick: 0,
//         },
//         material: [
//           {
//             rating_of_member: 0,
//             type_of_damages: [
//               {
//                 tick: 0,
//                 active_details: 0,
//                 name: "Inadequate Opening",
//                 code: 38,
//                 severity_of_damage: 0,
//                 percentage_affected: "",
//                 remarks: "",
//                 severity_of_damage_list: damage38,
//                 type_of_damages_array: typeOfDamage38,
//               },
//             ],
//           },
//         ],
//       },
//     });

//     const createTollList = await prisma.toll_list.createMany({
//       data: [
//         {
//           structure: Toll_Component_1,
//           position: 1,
//         },
//         {
//           structure: Toll_Component_2,
//           position: 2,
//         },
//         {
//           structure: Toll_Component_3,
//           position: 3,
//         },
//         {
//           structure: Toll_Component_4,
//           position: 4,
//         },
//         {
//           structure: Toll_Component_5,
//           position: 5,
//         },
//         {
//           structure: Toll_Component_6,
//           position: 6,
//         },
//         {
//           structure: Toll_Component_7,
//           position: 7,
//         },
//         {
//           structure: Toll_Component_8,
//           position: 8,
//         },
//         {
//           structure: Toll_Component_9,
//           position: 9,
//         },
//         {
//           structure: Toll_Component_10,
//           position: 10,
//         },
//       ],
//     });

//     // if (create && create2 && create3) {
//     if (createTollList) {
//       return new NextResponse("Successfully Populate toll_list table.");
//     } else {
//       return new NextResponse("Fail");
//     }
//   } catch (error: any) {
//     return new NextResponse(error.message);
//   }
// }
